# perms:
# bet.command.start -> perm for start bet process
# bet.command.stop -> perm for stop bet process

time-zone: "GMT+3" #Moscow time

#s - seconds; m - minutes; h - hours
interval: 24h # Daily interval

menu-rows: 3 # GUI Menu size. How many rows there.

# SUPPORTED: ["Vault", "-Reserve-", "MultiEconomy", "-CoinsEngine-"]
# NOTE: "Vault" does not support separated economies. It would add money to both plugin's "accounts"
economy-from: "Vault" # Economy to take money from
economy-to: "MultiEconomy" # Economy to give money to

# OPTIONAL (Supported: ["MultiEconomy", "CoinsEngine"])
economy-from-currency: "gems"
economy-to-currency: "gems"
