name: DailyBet
version: '${project.version}'
main: ru.legeu.dailybet.DailyBet
api-version: '1.20'
authors: [Legeu]
depend: [Vault, PlayerPoints, CoinsEngine, nightcore]
load: POSTWORLD
commands:
  bet: {}