name: DailyBet
version: '0.1-1.20.4'
main: com.megadev.dailybet.DailyBet
api-version: '1.20'
authors: [Legeu, Dreaght]
depend: [Vault, PlayerPoints, CoinsEngine, nightcore]
load: POSTWORLD
commands:
  bet: {}