name: DailyBet
version: '0.1-1.20.4'
main: com.megadev.dailybet.DailyBet
api-version: '1.16'
authors: [Legeu, Dreaght]
softdepend: [CoinsEngine, Vault, nightcore, MultiEconomy]
load: POSTWORLD
commands:
  bet: {}